export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CHAT_ROUTE = '/chats'
export const ADMIN_ROUTE = '/admin'
export const SOCKET_URL = 'ws://localhost:8900'